### ISSUE TITLE
error in CurrentDomain

### ISSUE THREAD

**Issue by consigliory** [stormpath/stormpath-sdk-angular#72]
Exception: Call to Node module failed with error: ReferenceError: window is not defined
at new CurrentDomain (/Users/source/elixir/Client/dist/main-server.js:9727:23)
at new Stormpath (/Users/source/elixir/Client/dist/main-server.js:286:30)
at NgModuleInjector.get (/AppServerModule/module.ngfactory.js:459:65).

**Comment by consigliory** [comment]
do you have any plans to provide support for angular universal or angular 4?

**Comment by mraible** [comment]
@consigliory Yes, it's something I'd like to do. However, based on today's announcement - [Stormpath is joining forces with Okta](https://stormpath.com/blog/stormpaths-new-path?utm_source=github&utm_medium=readme&utm-campaign=okta-announcement) - I don't know if I'll be able to.
